# 11주차 과제

아래와 같은 흑백이미지가 있다고 하자. 
```
0 0 0 1 1 1 
0 0 0 1 1 1 
0 0 0 1 1 1 
0 0 0 1 1 1 
0 0 0 1 1 1
0 0 0 1 1 1 
```

위의 이미지에 아래와 같은 weight를 가진 필터를 적용하여 convolution한 결과를 계산하라. (bias는 0으로 가정한다) 
```
-1 1 
-1 1 
```

In [1]:
import tensorflow as tf 
import tensorflow.experimental.numpy as tnp 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
tnp.experimental_enable_numpy_behavior()

In [24]:
XXX = tf.constant([[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1],[0,0,0,1,1,1]],dtype=tf.float64).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=float64, numpy=
array([[[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]]])>

In [25]:
cnv = tf.keras.layers.Conv2D(1,(2,2))

In [26]:
cnv.weights

[]

In [27]:
cnv(XXX).reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float32, numpy=
array([[[0.       , 0.       , 0.2497356, 0.7505721, 0.7505721],
        [0.       , 0.       , 0.2497356, 0.7505721, 0.7505721],
        [0.       , 0.       , 0.2497356, 0.7505721, 0.7505721],
        [0.       , 0.       , 0.2497356, 0.7505721, 0.7505721],
        [0.       , 0.       , 0.2497356, 0.7505721, 0.7505721]]],
      dtype=float32)>

In [28]:
cnv.weights

[<tf.Variable 'conv2d_2/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[ 0.81776005]],
 
         [[ 0.25589293]]],
 
 
        [[[-0.31692356]],
 
         [[-0.00615734]]]], dtype=float32)>,
 <tf.Variable 'conv2d_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [29]:
cnv.weights[0]

<tf.Variable 'conv2d_2/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
array([[[[ 0.81776005]],

        [[ 0.25589293]]],


       [[[-0.31692356]],

        [[-0.00615734]]]], dtype=float32)>

In [30]:
_w = tf.constant([[-1,1],[-1,1]],dtype=tf.float64).reshape(2,2,1,1)
_b = tf.constant([0],dtype=tf.float64)

In [31]:
cnv.set_weights([_w,_b])

In [32]:
cnv.weights

[<tf.Variable 'conv2d_2/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[-1.]],
 
         [[ 1.]]],
 
 
        [[[-1.]],
 
         [[ 1.]]]], dtype=float32)>,
 <tf.Variable 'conv2d_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [33]:
cnv(XXX).reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float32, numpy=
array([[[0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.]]], dtype=float32)>