In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import tensorflow.experimental.numpy as tnp

In [2]:
tnp.experimental_enable_numpy_behavior()

In [3]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
28*28

784

In [7]:
X = tf.constant(x_train.reshape(-1,28,28,1),dtype=tf.float64)
y = tf.keras.utils.to_categorical(y_train)
XX = tf.constant(x_test.reshape(-1,28,28,1),dtype=tf.float64)
yy = tf.keras.utils.to_categorical(y_test)

`-` 첫시도

In [13]:
net1 = tf.keras.Sequential()
net1.add(tf.keras.layers.Flatten())
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(10,activation='softmax'))
net1.compile(loss=tf.losses.categorical_crossentropy, optimizer='adam',metrics=['accuracy'])
net1.fit(X,y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 17s 9ms/step - loss: 1.4113 - accuracy: 0.7825
Epoch 2/5
1875/1875 [==============================] - 18s 10ms/step - loss: 0.4573 - accuracy: 0.8363
Epoch 3/5
1875/1875 [==============================] - 18s 9ms/step - loss: 0.4169 - accuracy: 0.8508
Epoch 4/5
1875/1875 [==============================] - 17s 9ms/step - loss: 0.3969 - accuracy: 0.8595
Epoch 5/5
1875/1875 [==============================] - 20s 11ms/step - loss: 0.3754 - accuracy: 0.8649


In [14]:
net1.evaluate(XX,yy)

313/313 [==============================] - 1s 4ms/step - loss: 0.4110 - accuracy: 0.8567


[0.411011278629303, 0.8567000031471252]

In [15]:
net1.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 784)               0         
                                                                 
 dense_10 (Dense)            (None, 500)               392500    
                                                                 
 dense_11 (Dense)            (None, 500)               250500    
                                                                 
 dense_12 (Dense)            (None, 500)               250500    
                                                                 
 dense_13 (Dense)            (None, 10)                5010      
                                                                 
Total params: 898,510
Trainable params: 898,510
Non-trainable params: 0
_________________________________________________________________


`-` 두번째 시도

In [ ]:
tf.keras.layers.Conv2D

In [ ]:
tf.keras.layers.MaxPool2D

In [26]:
net2 = tf.keras.Sequential()
net2.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net2.add(tf.keras.layers.MaxPool2D())
net2.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net2.add(tf.keras.layers.MaxPool2D())
net2.add(tf.keras.layers.Flatten())
net2.add(tf.keras.layers.Dense(10,activation='softmax'))
net2.compile(loss=tf.losses.categorical_crossentropy, optimizer='adam',metrics=['accuracy'])
net2.fit(X,y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 54s 29ms/step - loss: 0.7907 - accuracy: 0.8077
Epoch 2/5
1875/1875 [==============================] - 57s 30ms/step - loss: 0.3659 - accuracy: 0.8695
Epoch 3/5
1875/1875 [==============================] - 53s 28ms/step - loss: 0.3247 - accuracy: 0.8829
Epoch 4/5
1875/1875 [==============================] - 54s 29ms/step - loss: 0.3044 - accuracy: 0.8905
Epoch 5/5
1875/1875 [==============================] - 54s 29ms/step - loss: 0.2899 - accuracy: 0.8944


In [27]:
net2.evaluate(XX,yy)

313/313 [==============================] - 2s 6ms/step - loss: 0.3451 - accuracy: 0.8743


[0.3450699746608734, 0.8743000030517578]

In [28]:
net2.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 27, 27, 30)        150       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 13, 13, 30)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 12, 12, 30)        3630      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 6, 6, 30)         0         
 2D)                                                             
                                                                 
 flatten_5 (Flatten)         (None, 1080)              0         
                                                                 
 dense_15 (Dense)            (None, 10)               

In [29]:
net2.layers

In [30]:
c1, m1, c2, m2, flttn, dns = net2.layers

In [31]:
print(X.shape) # 입력이미지 = 2D
print(c1(X).shape) # 2D
print(m1(c1(X)).shape) # 2D
print(c2(m1(c1(X))).shape) # 2D
print(m2(c2(m1(c1(X)))).shape) # 2D
print(flttn(m2(c2(m1(c1(X))))).shape) # 1D
print(dns(flttn(m2(c2(m1(c1(X)))))).shape) # 1D

(60000, 28, 28, 1)
(60000, 27, 27, 30)
(60000, 13, 13, 30)
(60000, 12, 12, 30)
(60000, 6, 6, 30)
(60000, 1080)
(60000, 10)


### maxpooling

#### 테스트1

`-` 레이어생성

In [32]:
m=tf.keras.layers.MaxPool2D()

In [33]:
m

`-` 입력데이터

In [34]:
XXX = tnp.arange(1*4*4*1).reshape(1,4,4,1)
XXX

<tf.Tensor: shape=(1, 4, 4, 1), dtype=int64, numpy=
array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]]])>

In [35]:
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])>

`-` 입력데이터가 레이어를 통과한 모습

In [37]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[ 5,  7],
        [13, 15]]])>

`-` MaxPool2D layer의 역할 : (2,2) 윈도우를 만들고 (2,2) 윈도우에서 max를 뽑아 값을 기록, 윈도우를 움직이면서 반복

#### 테스트2

In [38]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])>

In [39]:
m(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=int64, numpy=
array([[[ 7,  9, 11],
        [19, 21, 23],
        [31, 33, 35]]])>

#### 테스트3

In [41]:
m=tf.keras.layers.MaxPool2D(pool_size=(3,3))

In [42]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])>

In [43]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[14, 17],
        [32, 35]]])>

#### 테스트4

In [44]:
m=tf.keras.layers.MaxPool2D(pool_size=(2,2))

In [45]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])>

In [46]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[ 6,  8],
        [16, 18]]])>

In [47]:
m=tf.keras.layers.MaxPool2D(pool_size=(2,2),padding="same")

In [48]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])>

In [49]:
m(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=int64, numpy=
array([[[ 6,  8,  9],
        [16, 18, 19],
        [21, 23, 24]]])>

#### 테스트5

In [50]:
XXX = tnp.arange(2*4*4*1).reshape(2,4,4,1)
XXX.reshape(2,4,4)

<tf.Tensor: shape=(2, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])>

In [51]:
m(XXX).reshape(2,2,2)

<tf.Tensor: shape=(2, 2, 2), dtype=int64, numpy=
array([[[ 5,  7],
        [13, 15]],

       [[21, 23],
        [29, 31]]])>

#### 테스트6

In [52]:
XXX = tnp.arange(1*4*4*3).reshape(1,4,4,3)
XXX.reshape(1,4,4,3)

<tf.Tensor: shape=(1, 4, 4, 3), dtype=int64, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]]])>

In [53]:
XXX[:,:,:,0]

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33],
        [36, 39, 42, 45]]])>

In [54]:
XXX[...,0]

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33],
        [36, 39, 42, 45]]])>

In [56]:
m(XXX)

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int64, numpy=
array([[[[15, 16, 17],
         [21, 22, 23]],

        [[39, 40, 41],
         [45, 46, 47]]]])>

In [55]:
m(XXX)[...,0]

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[15, 21],
        [39, 45]]])>

### Convolution

#### test1

`-` 레이어생성

In [57]:
cnv=tf.keras.layers.Conv2D(1,(2,2))

In [58]:
cnv

`-` XXX생성

In [67]:
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1) # type이 float여야 에러가 안남.
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

In [68]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 6.5743356,  8.77266  , 10.970985 ],
        [15.367638 , 17.565962 , 19.764288 ],
        [24.160938 , 26.359262 , 28.557589 ]]], dtype=float32)>

- XXX에서 cnv(XXX)로 가는 맵핑을 찾는건 쉽지 않아보인다.
- 심지어 랜덤으로 결정되는 부분도 있어보임

`-` 코드정리 + 시드통일

In [69]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(2,2))
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1) 

In [70]:
print(XXX.reshape(1,4,4))
print(cnv(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ -4.125754   -5.312817   -6.4998803]
  [ -8.874006  -10.0610695 -11.248133 ]
  [-13.62226   -14.809322  -15.996386 ]]], shape=(1, 3, 3), dtype=float32)


In [71]:
cnv.weights

[<tf.Variable 'conv2d_6/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32)>,
 <tf.Variable 'conv2d_6/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [72]:
type(cnv.weights)

list

In [73]:
cnv.weights[0]

<tf.Variable 'conv2d_6/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
array([[[[-0.13014299]],

        [[-0.23927206]]],


       [[[-0.20175874]],

        [[-0.6158894 ]]]], dtype=float32)>

In [74]:
tf.reshape(cnv.weights[0],(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13014299, -0.23927206],
       [-0.20175874, -0.6158894 ]], dtype=float32)>

In [75]:
print(XXX.reshape(1,4,4))
print(cnv(XXX).reshape(1,3,3))

tf.Tensor(
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]], shape=(1, 4, 4), dtype=float64)
tf.Tensor(
[[[ -4.125754   -5.312817   -6.4998803]
  [ -8.874006  -10.0610695 -11.248133 ]
  [-13.62226   -14.809322  -15.996386 ]]], shape=(1, 3, 3), dtype=float32)


In [76]:
tf.reshape(cnv.weights[0],(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13014299, -0.23927206],
       [-0.20175874, -0.6158894 ]], dtype=float32)>

In [81]:
0 * (-0.13014299) + 1 * (-0.23927206) + 4 * (-0.20175874) + 5 * (-0.6158894) + 0

-4.1257540200000005

In [79]:
cnv.get_weights()

[array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32), array([0.], dtype=float32)]

In [80]:
cnv.weights

[<tf.Variable 'conv2d_6/kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
 array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32)>,
 <tf.Variable 'conv2d_6/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [82]:
cnv.get_weights()[0].shape

(2, 2, 1, 1)

In [89]:
w = np.array([1/4,1/4,1/4,1/4],dtype=np.float32).reshape(2,2,1,1)
b = np.array([3],dtype=np.float32)

In [90]:
[w,b]

[array([[[[0.25]],
 
         [[0.25]]],
 
 
        [[[0.25]],
 
         [[0.25]]]], dtype=float32), array([3.], dtype=float32)]

In [91]:
cnv.set_weights([w,b])

In [93]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 5.5,  6.5,  7.5],
        [ 9.5, 10.5, 11.5],
        [13.5, 14.5, 15.5]]], dtype=float32)>

In [95]:
np.mean([0,1,4,5])+3, np.mean([1,2,5,6])+3, np.mean([2,3,6,7])+3  

(5.5, 6.5, 7.5)

### conv2D의 동작 요약

`-` 요약

(1) size=(2,2)인 윈도우를 만듬.

(2) XXX에 윈도우를 통과시켜서 (2,2)크기의 sub XXX를 얻음. sub XXX의 각 원소에 conv2d.weights[0]의 각 원소를 element-wise하게 곱한다.

(3) (2)의 결과를 모두 더한다. 그리고 그 결과에 다시 conv2d.weights[1]을 수행

(4) 윈도우를 이동시키면서 반복!

#### test2

In [96]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(3,3))
XXX = tnp.arange(1*5*5*1,dtype=tf.float64).reshape(1,5,5,1) 

In [97]:
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]]])>

In [98]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 2.7395773 ,  2.2492638 ,  1.7589507 ],
        [ 0.2880106 , -0.20230293, -0.6926167 ],
        [-2.163556  , -2.6538692 , -3.1441827 ]]], dtype=float32)>

In [99]:
tf.reshape(cnv.weights[0],(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.08676198, -0.1595147 , -0.13450584],
       [-0.4105929 , -0.38366908,  0.07744962],
       [-0.09255642,  0.4915564 ,  0.20828158]], dtype=float32)>

In [100]:
XXX.reshape(1,5,5)[0,:3,:3]

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 0.,  1.,  2.],
       [ 5.,  6.,  7.],
       [10., 11., 12.]])>

In [102]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 2.7395773 ,  2.2492638 ,  1.7589507 ],
        [ 0.2880106 , -0.20230293, -0.6926167 ],
        [-2.163556  , -2.6538692 , -3.1441827 ]]], dtype=float32)>

In [101]:
tf.reduce_sum(XXX.reshape(1,5,5)[0,:3,:3] * tf.reshape(cnv.weights[0],(3,3)))

<tf.Tensor: shape=(), dtype=float64, numpy=2.739577144384384>

#### test3

In [109]:
XXX = tf.constant([[3,3,2,1,0],[0,0,1,3,1],[3,1,2,2,3],[2,0,0,2,2],[2,0,0,1,1]],dtype=tf.float64).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=float64, numpy=
array([[[3., 3., 2., 1., 0.],
        [0., 0., 1., 3., 1.],
        [3., 1., 2., 2., 3.],
        [2., 0., 0., 2., 2.],
        [2., 0., 0., 1., 1.]]])>

In [110]:
cnv = tf.keras.layers.Conv2D(1,(3,3))

In [111]:
cnv.weights

[]

In [112]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1.7157198, 2.9689512, 2.7728841],
        [2.4162838, 1.8230928, 2.9890852],
        [1.9408667, 0.9694788, 2.7528245]]], dtype=float32)>

In [113]:
cnv.weights

[<tf.Variable 'conv2d_9/kernel:0' shape=(3, 3, 1, 1) dtype=float32, numpy=
 array([[[[ 0.28270614]],
 
         [[-0.13318631]],
 
         [[ 0.21818542]]],
 
 
        [[[ 0.23769057]],
 
         [[ 0.40044254]],
 
         [[ 0.38520074]]],
 
 
        [[[ 0.15709132]],
 
         [[ 0.48156905]],
 
         [[-0.25362712]]]], dtype=float32)>,
 <tf.Variable 'conv2d_9/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [115]:
_w = tf.constant([[0,1,2],[2,2,0],[0,1,2]],dtype=tf.float64).reshape(3,3,1,1)
_b = tf.constant([0],dtype=tf.float64)

In [116]:
cnv.set_weights([_w,_b])

In [117]:
cnv(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[12., 12., 17.],
        [10., 17., 19.],
        [ 9.,  8., 15.]]], dtype=float32)>

#### test4

In [118]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(1,(2,2))
XXX = tnp.arange(2*5*5*1,dtype=tf.float64).reshape(2,5,5,1) 

In [121]:
XXX.reshape(2,5,5)

<tf.Tensor: shape=(2, 5, 5), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]],

       [[25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]]])>

In [125]:
w

array([[[[0.25]],

        [[0.25]]],


       [[[0.25]],

        [[0.25]]]], dtype=float32)

In [126]:
b

array([3.], dtype=float32)

In [124]:
cnv(XXX) # weight를 초기화하기 위해서 레이어를 1회 통과
cnv.set_weights([w,b])
cnv(XXX).reshape(2,4,4)

<tf.Tensor: shape=(2, 4, 4), dtype=float32, numpy=
array([[[ 6.,  7.,  8.,  9.],
        [11., 12., 13., 14.],
        [16., 17., 18., 19.],
        [21., 22., 23., 24.]],

       [[31., 32., 33., 34.],
        [36., 37., 38., 39.],
        [41., 42., 43., 44.],
        [46., 47., 48., 49.]]], dtype=float32)>

#### test5

In [128]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,(2,2))
XXX = tnp.arange(1*2*2*1,dtype=tf.float64).reshape(1,2,2,1) 

In [129]:
print(XXX.reshape(1,2,2))

tf.Tensor(
[[[0. 1.]
  [2. 3.]]], shape=(1, 2, 2), dtype=float64)


In [130]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 1.048703  , -1.0948269 , -0.04476056, -1.7289025 ]]]],
      dtype=float32)>

In [131]:
cnv.weights[0] # (2,2) 커널의 크기 // 1은 XXX의 채널수 // 4는 cnv(XXX)의 채널수

<tf.Variable 'conv2d_12/kernel:0' shape=(2, 2, 1, 4) dtype=float32, numpy=
array([[[[-0.08230966, -0.15132892, -0.12760344, -0.38952267]],

        [[-0.36398047,  0.07347518, -0.08780673,  0.46633136]]],


       [[[ 0.19759327, -0.46042526, -0.15406173, -0.34838456]],

        [[ 0.33916563, -0.08248386,  0.11705655, -0.49948823]]]],
      dtype=float32)>

In [132]:
cnv.weights[1]

<tf.Variable 'conv2d_12/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [134]:
cnv.weights[0][...,0].reshape(2,2) # cnv(XXX)의 첫번째 채널 출력을 얻기 위해 곱해지는 w

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08230966, -0.36398047],
       [ 0.19759327,  0.33916563]], dtype=float32)>

In [135]:
tf.reduce_sum(XXX.reshape(1,2,2) * cnv.weights[0][...,0].reshape(2,2)) # cnv(XXX)의 첫번째 채널 출력결과

<tf.Tensor: shape=(), dtype=float64, numpy=1.0487029552459717>

In [136]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 1.048703  , -1.0948269 , -0.04476056, -1.7289025 ]]]],
      dtype=float32)>

In [138]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,(2,2))
XXX = tnp.array([1]*1*2*2*1,dtype=tf.float64).reshape(1,2,2,1) 

In [140]:
print(XXX.reshape(1,2,2))

tf.Tensor(
[[[1. 1.]
  [1. 1.]]], shape=(1, 2, 2), dtype=float64)


In [142]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 0.09046876, -0.6207628 , -0.25241536, -0.7710641 ]]]],
      dtype=float32)>

`-` 이렇게 XXX를 설정하면 cnv(XXX)의 결과는 단지 cnv의 weight들의 sum이 된다.

In [143]:
tf.reduce_sum(XXX.reshape(1,2,2) * cnv.weights[0][...,0].reshape(2,2))

<tf.Tensor: shape=(), dtype=float64, numpy=0.09046876430511475>

In [144]:
tf.reduce_sum(cnv.weights[0][...,0].reshape(2,2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.090468764>

#### test6

In [146]:
tf.random.set_seed(43052)
cnv = tf.keras.layers.Conv2D(4,(2,2))
XXX = tnp.array([1]*1*2*2*3,dtype=tf.float64).reshape(1,2,2,3) 

In [147]:
cnv(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 0.3297621 , -0.44983467, -1.0487392 , -1.5800949 ]]]],
      dtype=float32)>

In [148]:
cnv.weights[0] # (2,2)는 커널의 사이즈 // 3은 XXX의 채널 // 4는 cnv(XXX)의 채널 

<tf.Variable 'conv2d_15/kernel:0' shape=(2, 2, 3, 4) dtype=float32, numpy=
array([[[[-0.06956434, -0.12789628, -0.10784459, -0.32920673],
         [-0.30761963,  0.06209785, -0.07421023,  0.3941219 ],
         [ 0.16699678, -0.38913035, -0.13020593, -0.29443866]],

        [[ 0.28664726, -0.0697116 ,  0.09893084, -0.4221446 ],
         [-0.23161241, -0.16410837, -0.36420006,  0.12424195],
         [-0.14245945,  0.36286396, -0.10751781,  0.1733647 ]]],


       [[[ 0.02764335,  0.15547717, -0.42024496, -0.31893867],
         [ 0.22414821,  0.3619454 , -0.00282967, -0.3503708 ],
         [ 0.4610079 , -0.17417148,  0.00401336, -0.29777044]],

        [[-0.1620284 , -0.42066965, -0.01578814, -0.4240524 ],
         [ 0.37925082,  0.24236053,  0.3949356 , -0.20996472],
         [-0.30264795, -0.28889188, -0.3237777 ,  0.37506342]]]],
      dtype=float32)>

In [149]:
cnv.weights[0][...,0] # cnv(XXX)의 첫번째 채널결과를 얻기 위해서 사용하는 w

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.06956434, -0.30761963,  0.16699678],
        [ 0.28664726, -0.23161241, -0.14245945]],

       [[ 0.02764335,  0.22414821,  0.4610079 ],
        [-0.1620284 ,  0.37925082, -0.30264795]]], dtype=float32)>

In [150]:
tf.reduce_sum(cnv.weights[0][...,0]) # cnv(XXX)의 첫번째 채널의 결과

<tf.Tensor: shape=(), dtype=float32, numpy=0.3297621>

In [154]:
print(tf.reduce_sum(cnv.weights[0][...,0]))
print(tf.reduce_sum(cnv.weights[0][...,1]))
print(tf.reduce_sum(cnv.weights[0][...,2]))
print(tf.reduce_sum(cnv.weights[0][...,3]))

tf.Tensor(0.3297621, shape=(), dtype=float32)
tf.Tensor(-0.44983464, shape=(), dtype=float32)
tf.Tensor(-1.0487392, shape=(), dtype=float32)
tf.Tensor(-1.5800952, shape=(), dtype=float32)


In [159]:
cnv.weights[0][...,0]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.06956434, -0.30761963,  0.16699678],
        [ 0.28664726, -0.23161241, -0.14245945]],

       [[ 0.02764335,  0.22414821,  0.4610079 ],
        [-0.1620284 ,  0.37925082, -0.30264795]]], dtype=float32)>

In [156]:
w_red = cnv.weights[0][...,0][...,0]
w_green = cnv.weights[0][...,0][...,1]
w_blue = cnv.weights[0][...,0][...,2]  

In [157]:
w_red

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.06956434,  0.28664726],
       [ 0.02764335, -0.1620284 ]], dtype=float32)>

In [158]:
XXX[...,0] # X_red

<tf.Tensor: shape=(1, 2, 2), dtype=float64, numpy=
array([[[1., 1.],
        [1., 1.]]])>

In [160]:
tf.reduce_sum(XXX[...,0] * w_red + XXX[...,1] * w_green + XXX[...,2] * w_blue) # cnv(XXX)의 첫번째 채널출력 결과

<tf.Tensor: shape=(), dtype=float64, numpy=0.32976213097572327>